// The BR-first rule model: mirrors .claude/rules/_index.json (generated by
// extract-brs.mjs). Rules are the atomic spec unit; the app composes state by
// folding their deltas up to a cut.

export interface RuleDeltaOps {
  add?: string[];
  modify?: string[];
  remove?: string[];
}
export type RuleDelta = Record<string, RuleDeltaOps>;

export interface RuleEntry {
  name: string;
  seq: string;            // Dewey-decimal ordinal string, the sole order source
  features: string[];
  modifiesFeatures: string[];
  dependsOn: string[];    // context only (by slug)
  category: string;
  delta: RuleDelta;
  legacyUc?: string;      // provenance — lets the BR Net (keyed by UC) drive the feature cut
}

export const DELTA_KINDS = ['entities', 'endpoints', 'slices', 'components', 'selectors'] as const;
export type DeltaKind = (typeof DELTA_KINDS)[number];

export interface ComposedArtifact {
  target: string;
  owner: string;          // feature that introduced it
  modifiedBy: string[];   // features that later changed it
}
export interface CrossFeatureChange {
  from: string;
  to: string;
  kind: string;
  target: string;
}
export interface ComposedState {
  kinds: Record<string, ComposedArtifact[]>;
  crossFeature: CrossFeatureChange[];
  included: number;
  total: number;
  cutSeq: string;
}
export interface FeatureInfo {
  name: string;
  minSeq: string;
  maxSeq: string;
  count: number;
}

/** Dewey comparison: segment-wise numeric; shorter prefix sorts first. */
export function deweyCompare(a: string, b: string): number {
  const A = String(a).split('.').map(Number);
  const B = String(b).split('.').map(Number);
  for (let i = 0; i < Math.max(A.length, B.length); i++) {
    const x = A[i] ?? -1;
    const y = B[i] ?? -1;
    if (x !== y) return x - y;
  }
  return 0;
}

/** Features in development order (by their earliest rule). */
export function featuresInOrder(rules: RuleEntry[]): FeatureInfo[] {
  const byFeature = new Map<string, RuleEntry[]>();
  for (const r of rules) {
    for (const f of r.features ?? []) {
      (byFeature.get(f) ?? byFeature.set(f, []).get(f)!).push(r);
    }
  }
  const infos: FeatureInfo[] = [];
  for (const [name, rs] of byFeature) {
    const seqs = rs.map((r) => r.seq).sort(deweyCompare);
    infos.push({ name, minSeq: seqs[0], maxSeq: seqs[seqs.length - 1], count: rs.length });
  }
  return infos.sort((a, b) => deweyCompare(a.minSeq, b.minSeq));
}

/** The seq cut for a feature = its highest-seq rule. */
export function featureCut(rules: RuleEntry[], feature: string): string {
  const rs = rules.filter((r) => (r.features ?? []).includes(feature));
  return rs.reduce((m, r) => (deweyCompare(r.seq, m) > 0 ? r.seq : m), rs[0]?.seq ?? '0');
}

/** Fold every rule with seq <= cut into the composed application state. */
export function foldTo(rules: RuleEntry[], cutSeq: string): ComposedState {
  const included = rules
    .filter((r) => deweyCompare(r.seq, cutSeq) <= 0)
    .sort((a, b) => deweyCompare(a.seq, b.seq));

  const state: Record<string, Map<string, ComposedArtifact>> = {};
  for (const k of DELTA_KINDS) state[k] = new Map();
  const crossFeature: CrossFeatureChange[] = [];
  const seen = new Set<string>();

  for (const r of included) {
    const feat = (r.features ?? [])[0] ?? '(none)';
    for (const kind of DELTA_KINDS) {
      const d = r.delta?.[kind];
      if (!d) continue;
      for (const t of d.add ?? []) {
        if (!state[kind].has(t)) state[kind].set(t, { target: t, owner: feat, modifiedBy: [] });
      }
      for (const t of d.modify ?? []) {
        const cur = state[kind].get(t);
        if (!cur) continue;
        if (!cur.modifiedBy.includes(feat)) cur.modifiedBy.push(feat);
        if (cur.owner !== feat) {
          const key = `${feat}->${cur.owner}:${kind}:${t}`;
          if (!seen.has(key)) { seen.add(key); crossFeature.push({ from: feat, to: cur.owner, kind, target: t }); }
        }
      }
    }
  }

  const kinds: Record<string, ComposedArtifact[]> = {};
  for (const k of DELTA_KINDS) kinds[k] = [...state[k].values()];
  return { kinds, crossFeature, included: included.length, total: rules.length, cutSeq };
}
